---
- hosts: all
  become: true

  tasks:
    - name: Update repos
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the host if needed
      reboot:
        msg: "Reboot started by Anible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

- hosts: dns

  tasks:
    - name: Update PiHole
      ansible.builtin.command: pihole -up

- hosts: game

  tasks:
    - name: Restart game service
      ansible.builtin.command: game-startup
